# Generated by Django 4.2.3 on 2023-07-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('synonyms', models.JSONField(blank=True, default=list, help_text='JSON array of synonyms.', null=True)),
                ('antonyms', models.JSONField(blank=True, default=list, help_text='JSON array of antonyms.', null=True)),
            ],
        ),
    ]
